### ISSUE TITLE
Unexpected token 'run.lua' in expression or statement.

### ISSUE THREAD

**Issue by apostoloskotsiras** [JustAPerson/lbi#2]
At line:1 char:6
+ $lua run.lua
+      ~~~~~~~
Unexpected token 'run.lua' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by JustAPerson** [comment]
It looks like you're not using a typical shell? Hard to tell.
Try using bash.

**Comment by Cube9999** [comment]
This sounds like he is using powershell. So he is most likely running on windows and not a unix-like system
